javascript:(()=>{const ID='blooket-qol-menu';const STYLE_ID='blooket-qol-style';const state={fontScale:1,dark:false,hideSidebar:false};const ensureStyle=()=>{if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
#${ID}{position:fixed;top:16px;right:16px;z-index:2147483647;background:#0f172a;color:#e2e8f0;border:1px solid #334155;border-radius:12px;min-width:260px;box-shadow:0 12px 30px rgba(0,0,0,.45);font:14px/1.4 system-ui,-apple-system,Segoe UI,Roboto,sans-serif}
#${ID} *{box-sizing:border-box}
#${ID} .hdr{display:flex;justify-content:space-between;align-items:center;padding:10px 12px;border-bottom:1px solid #334155;font-weight:700}
#${ID} .body{padding:10px 12px;display:grid;gap:8px}
#${ID} button,#${ID} a{all:unset;display:block;padding:8px 10px;background:#1e293b;border:1px solid #334155;border-radius:8px;cursor:pointer}
#${ID} button:hover,#${ID} a:hover{background:#334155}
#${ID} .row{display:grid;grid-template-columns:1fr 1fr;gap:8px}
#${ID} .muted{font-size:12px;color:#94a3b8}
.blooket-qol-dark{filter:invert(1) hue-rotate(180deg)}
.blooket-qol-dark img,.blooket-qol-dark video,.blooket-qol-dark canvas{filter:invert(1) hue-rotate(180deg)}
`;document.head.appendChild(s)};const setScale=(delta)=>{state.fontScale=Math.min(1.5,Math.max(0.8,+(state.fontScale+delta).toFixed(1)));document.documentElement.style.fontSize=`${state.fontScale*100}%`;msg(`Text scale: ${Math.round(state.fontScale*100)}%`)};const toggleDark=()=>{state.dark=!state.dark;document.documentElement.classList.toggle('blooket-qol-dark',state.dark);msg(`Dark mode ${state.dark?'on':'off'}`)};const toggleSidebar=()=>{state.hideSidebar=!state.hideSidebar;const selectors=['aside','[class*=sidebar]','[class*=Sidebar]','[class*=nav]'];selectors.forEach(sel=>document.querySelectorAll(sel).forEach(el=>{el.style.display=state.hideSidebar?'none':''}));msg(state.hideSidebar?'Likely sidebars hidden':'Likely sidebars restored')};const msg=(text)=>{const el=document.getElementById(`${ID}-msg`);if(el)el.textContent=text};const open=(path)=>window.location.href=`https://www.blooket.com${path}`;const existing=document.getElementById(ID);if(existing){existing.remove();return;}ensureStyle();const menu=document.createElement('div');menu.id=ID;menu.innerHTML=`<div class="hdr">Blooket QoL Menu <button id="${ID}-x" title="Close">✕</button></div><div class="body"><div class="row"><button id="${ID}-a11y-plus">A+ text</button><button id="${ID}-a11y-minus">A- text</button></div><div class="row"><button id="${ID}-dark">Toggle dark mode</button><button id="${ID}-hide">Toggle sidebar</button></div><div class="row"><button id="${ID}-dash">Dashboard</button><button id="${ID}-sets">Discover Sets</button></div><button id="${ID}-hw">Homework</button><div class="muted" id="${ID}-msg">Local-only helper. No cheats.</div></div>`;document.body.appendChild(menu);document.getElementById(`${ID}-x`).onclick=()=>menu.remove();document.getElementById(`${ID}-a11y-plus`).onclick=()=>setScale(0.1);document.getElementById(`${ID}-a11y-minus`).onclick=()=>setScale(-0.1);document.getElementById(`${ID}-dark`).onclick=toggleDark;document.getElementById(`${ID}-hide`).onclick=toggleSidebar;document.getElementById(`${ID}-dash`).onclick=()=>open('/dashboard');document.getElementById(`${ID}-sets`).onclick=()=>open('/discover');document.getElementById(`${ID}-hw`).onclick=()=>open('/homework');})();
